### PR TITLE
[Fixes 1138] Timeline throws error and not displaying correctly the features

### PR DESCRIPTION
**Pull request by DavidQuartz**
The mapstore submodule has been checked out to the right stable branch which includes the fixes.
Screenshot of error fixed

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@marthamareal please test this on dev as soon as the new bundle is deployed and let us know when we can backport to stable branch 4.x, thanks

**Comment by marthamareal** [comment]
@DavidQuartz, @allyoucanmap I still see the error in the console as shown in the issue. see screenshot below

**Comment by allyoucanmap** [comment]
@marthamareal I think the new bundle was not merged on friday, I just merged it now. Could you retry again as soon as the new geonode build is ready? thanks

**Comment by giohappy** [comment]
I confirm it works now on master.

**Pull request merged**
