### PR TITLE
Set thumbnail from map inside datasets and maps detail panel

### PR DESCRIPTION
**Pull request by luorlandini**
Set thumbnail from map inside datasets and maps detail panel

https://user-images.githubusercontent.com/4085786/124913827-e2316d80-dfef-11eb-9371-72e5e4a46cae.mov

### CODE REVIEW

**Comment by luorlandini** [comment]
@giohappy  to set the map/layer thumbnail, the api  we use responds with a string, an improvement could be to have it in json format and if successful, have the thumbnail url, to have fewer calls to the BE

**Comment by giohappy** [comment]
The legacy thumbnail API will remain for a while since legacy pages (metadata) still use it.
If it's a blocker ok, we can implement an improved API and adapt the legacy UI to adopt it. If you can cope with the current limitations let's go on.

**Comment by luorlandini** [comment]
@giohappy it's not blocking, it was just a notification of improvement

**Comment by giohappy** [comment]
@luorlandini I've reviewed the legacy thumbnail API and I agree with you to implement a new API v2 endpoint, that will return the thumbnail URL inside the response. 
Let's keep this PR on hold, the endpoint implementation should be quick.

**Comment by giohappy** [comment]
@luorlandini new API is ready. The new endpoint is `datasets/{pk}/set_thumbnail_from_bbox`. It expects the same POST body as the previous one, which has been dropped on master but is still available on stable demo if you need to give it a look.

**Pull request closed without merging**
