### PR TITLE
[Backport 4.0.x][Fixes #1192] Geonode Download filtered dataset, where filter is based on another layer

### LINKED ISSUE #1192: Geonode Download filtered dataset, where filter is based on another layer
@nagyrobir commented on [Tue Aug 16 2022](https://github.com/GeoNode/geonode/issues/9856)

## Expected Behavior
I have a point layer uploaded in Geonode, via the QGIS geonode plugin. I can view the dataset, everything works as expected.
I have a polygon layer created through geonode with one polygon. Works as expected.
When i try to filter the point layer by the polygon layer, the filtering works as expected.
When i try to download the filtered dataset, i would expect to be able to download it, the same way as when i hand draw the polygon filter without using the polygon layer.

## Actual Behavior
When i try to download the filtered dataset then i get the error message from the image attached.
If i filter the point layer by a polygon that i hand draw, to be explicit, without the use of the polygon layer that i created manually,then i can export the filtered dataset without any problem

download_failed

Download all the points from the points layer, which intersect the polygon that i am drawing myself during the filtering -> Works!
Download all the points from the points layer, which intersect the polygon that is in the polygon layer - > Does not work.

## Steps to Reproduce the Problem

  1.Get a point layer
  2.Get a polygon layer
  3.Intersect the point layer by the polygon layer
  4. Try to download the filtered dataset. 

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform:Linux
  - Additional details:

---

@marthamareal commented on [Mon Sep 05 2022](https://github.com/GeoNode/geonode/issues/9856#issuecomment-1236905242)

This error is similar to the one raised when you try to export a map layer with the `Layer filter` option enabled.
**Steps to reproduce**:
- Open a map with a dataset
- Select a layer and apply filters and save
b
- Export the layer with both options enabled, and the error will be raised
b2

b3

**NOTE: Export works fine if `Layer filter ` is not enabled**

### PR DESCRIPTION
**Pull request by DavidQuartz**
ref #1192 

Submodule updated with fix

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@marthamareal please test this fix on development, thanks

**Comment by marthamareal** [comment]
@DavidQuartz THis is failing for the GeoPackage option. using this as an example https://development.demo.geonode.org/catalogue/#/map/495

**Comment by DavidQuartz** [comment]
@marthamareal I just tried with the example you provided and it worked
Screenshot 2022-10-10 at 10 00 49

Can you provide the request payload and response when you try?
Also can you share some information about the environment you are testing in?

**Comment by marthamareal** [comment]
I have tried again and it's now downloading just fine. Not sure why it failed two times before because i did not read through the requests and responses. I think it can be marked as done.

**Pull request merged**
