### PR TITLE
[Backport 4.x] [Fixes 1138] Timeline throws error and not displaying correctly the features

### PR DESCRIPTION
**Pull request by DavidQuartz**
The mapstore submodule has been checked out to the right stable branch which includes the fixes.
Screenshot of error fixed

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@marthamareal please test on development, thanks

**Comment by marthamareal** [comment]
@allyoucanmap is the build merged and  deployed in development? because i still see the error on testing

**Comment by allyoucanmap** [comment]
I saw that some datasets with date are not correctly configured because WMTS is throwing error GeoServer side:

https://development.demo.geonode.org/catalogue/#/dataset/449
image

if you uploaded the dataset above recently means there is something not working as expected in the import.

If you try this older one, it works as expected
https://development.demo.geonode.org/catalogue/#/dataset/165

cc @giohappy

**Comment by giohappy** [comment]
@marthamareal please try to replicate the problem and share the shapefile in case it happens again.

**Comment by marthamareal** [comment]
For the example shared by @allyoucanmap, The error is thrown if you move the timeline to a year above 2000.
For the dataset, i uploaded, I have features in 2000, however, on adjusting the timeline to 2000, no changes reflect, and the error is thrown. attached are the files i uploaded.

[boxes_with_date.zip](https://github.com/GeoNode/geonode-mapstore-client/files/9402020/boxes_with_date.zip)


Are there specific steps am missing while testing this?

**Comment by allyoucanmap** [comment]
@marthamareal I just uploaded the shapefile you provided and it seems to work
https://development.demo.geonode.org/catalogue/#/dataset/451

image

Could you describe the steps you are doing in this page? Are you clicking directly on next?

image

> For the example shared by @allyoucanmap, The error is thrown if you move the timeline to a year above 2000.

Could you describe also the steps for this bug?

**Comment by marthamareal** [comment]
Yes I click next. Then later i change in metadata and enable the `has time` option

**Comment by allyoucanmap** [comment]
@marthamareal I think that's the issue, if you enable the metadata `has time` but you upload a dataset that has not been imported with a data/time field the configuration between GeoServer and GeoNode will be inconsistent. Here I think there is a UX issue because `has time` options should not be available in metadata if the layer does not support time dimension @giohappy

**Comment by giohappy** [comment]
@allyoucanmap this will change soon, once we have implemented the configuration of the time dimension from inside the metadata page.

**Pull request merged**
