### PR TITLE
[Fixes 1226] Embedded maps should have the timeline plugin

### PR DESCRIPTION
**Pull request by DavidQuartz**
Timeline has been activated in Map and Dataset preview and embed views

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@marthamareal please test on master and let us know when we can backport on 4.0.x, thanks

**Comment by marthamareal** [comment]
@DavidQuartz I can not see the timeline with the embed link https://master.demo.geonode.org/maps/2883/embed#/.

**Comment by marthamareal** [comment]
@DavidQuartz Timeline is now available on the embedded map. This PR can be backported to 4.0.x

**Comment by marthamareal** [comment]
@DavidQuartz Timeline is now available on the embedded map. This PR can be backported to 4.0.x

**Pull request merged**
