### PR TITLE
[Fixes #946] Autoclose info panel on single click on the map

### LINKED ISSUE #946: Autoclose info panel on single click on the map
The info panel is visible by default for datasets (not for maps). That's fine, but it must be hidden when a user does a single click on the map and a GFI is triggered, otherwise the result panel is hidden by the info panel.

hide_info_panel

### PR DESCRIPTION
**Pull request by DavidQuartz**
Both info and share panels are closed (if open) on map click

infopanel

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by DavidQuartz** [comment]
> Could you check if this fix will work with a pan interaction on the map?

The panel stays open on pan interactions as agreed for now. @allyoucanmap

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@marthamareal please test on master after the build has been merged and let us know if we can backport this on 4.x

**Comment by marthamareal** [comment]
@allyoucanmap This is working fine on master.

**Comment by marthamareal** [comment]
@allyoucanmap This is working fine on master.

**Pull request merged**
