### PR TITLE
[Fixes 1216] Remove uploaded items from new importer upload list on refresh 

### PR DESCRIPTION
**Pull request by DavidQuartz**

### CODE REVIEW

**Comment by giohappy** [comment]
@DavidQuartz built and tested, it looks good

**Comment by DavidQuartz** [comment]
@marthamareal please test this for backporting

**Comment by marthamareal** [comment]
@DavidQuartz uploaded items are still in the list after refresh

**Comment by giohappy** [comment]
@marthamareal I've renamed the PR and the connected issues, since the goal is removing the items when the user click View, not on refresh.
For the moment we hven't a way to automatically remove them on refresh, and probably this isn't what we really want...

**Comment by marthamareal** [comment]
@DavidQuartz, THis can be backported. it works as explained in @giohappy's comment.

**Pull request merged**
