### PR TITLE
[Backport 4.x] [Fixes #1022] Thumbnail placeholders 

### LINKED ISSUE #1022: Thumbnail placeholders
The current grey box must be replaced with a nice-looking default thumbnail.

Each data type should have a colored default thumbnail. It could simply be a white background with a blue icon. For the moment the icons currently adopted to distinguish resource types might be ok.

### PR DESCRIPTION
**Pull request by DavidQuartz**
ref #1022 

The current grey box has been replaced with a nice-looking default thumbnail.
For resource cards 
Screenshot 2022-08-05 at 10 16 52

For Info Panel (when user has no edit permission)
Screenshot 2022-08-05 at 10 17 45

For info panel (when user has edit permission) a base64 image of a white background has been used in the interim, to preserve the Thumnbnail component from Mapstore
Screenshot 2022-08-05 at 10 17 54

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@marthamareal please test on development, thanks

**Comment by allyoucanmap** [comment]
@marthamareal it seems the server is returning a url for the thumbnail there, maybe is it missing some fixes backend side on 4.x? cc @giohappy 

image

**Comment by marthamareal** [comment]
True @allyoucanmap, The backend PR was not backported. Let me backport it and test it again when its merged.

**Comment by marthamareal** [comment]
It's now working as expected.

**Pull request merged**
