### PR TITLE
#1710 - Update calls with catalog_list preset

### PR DESCRIPTION
**Pull request by dsuren1**
### Description
This PR adds catalog_list preset to required service calls. Added new presets (**Note**: few presets are not integrated yet on the client code. To be tested after this PR is merged)

> [!NOTE]
Branch is active in development.demo and under testing

### Issue
- #1710

### CODE REVIEW

**Comment by giohappy** [comment]
@dsuren1 branch is deployed and built on dev demo.

**Comment by giohappy** [comment]
@dsuren1 I guess `data` could be removed from the `catalog_list` preset, right?
If confirmed you can remove it inside this PR

**Comment by giohappy** [comment]
@etj we're introducing additional presets in this PR.
@dsuren1 is asking if the backend could ignore fields requested in a preset which are not supported by the current endpoint. An example is the [viewer](https://github.com/GeoNode/geonode-mapstore-client/pull/1711/files#diff-530fba68de7b7f41df76dc1fecb43cb63016bd46bd898aca337c2736c696b192R206) preset. It could be used for the different types of resources if it would simply ignore fields that are not supported by a specific resource, instead of throwing an error.
Otherwise, multiple presets must be defined for the different resource types.

**Comment by etj** [comment]
> @dsuren1 is asking if the backend could ignore fields requested in a preset which are not supported by the current endpoint. 

Nope, the preset handler simply replaces the preset query param with the configured params. 
The [issue description](https://github.com/GeoNode/geonode/issues/12104) clearly states:

> The filter will only expand a preset wherever it is declared. It does not know whether the called entrypoint will really deal with the parameters, so it will be up to the client to make sure the preset will really work with the requested operation.

**Comment by giohappy** [comment]
>Nope, the preset handler simply replaces the preset query param with the configured params.
The https://github.com/GeoNode/geonode/issues/12104 clearly states:

@dsuren1 in that case we could avoid duplicating the fields inside multiple presets by using a common configuration and then use it for the different presets. Something like this:

```
viewer_common_fields = ["field_1', 'field_2,' 'fields_3']
settings.REST_API_PRESETS["dataset_viewer"] = {
	"exclude[]": ["*"],
	"include[]": viewer_common_fields + [
		'field_4'
	]
	
settings.REST_API_PRESETS["map_viewer"] = {
	"exclude[]": ["*"],
	"include[]": viewer_common_fields + [
		'field_5'
	]
```

**Review by giohappy — APPROVED** [review]

**Pull request merged**
