### PR TITLE
[Fixes #976] Fix missing required accessToken for MapBox background when adding a map to a geostory

### LINKED ISSUE #976: Fix missing required accessToken for MapBox background when adding a map to a geostory
Fix missing required accessToken for MapBox background when adding a map to a geostory

### PR DESCRIPTION
**Pull request by mattiagiupponi**
Fix missing required accessToken for MapBox background when adding a map to a geostory

### CODE REVIEW

**Comment by giohappy** [comment]
@allyoucanmap as agreed let's check if this improvement can be done upstream in MapStore2, rather then inside the GeoNode client.

**Review by giohappy — COMMENTED** [review]
@allyoucanmap as agreed let's check if this improvement can be done upstream in MapStore2, rather then inside the GeoNode client.

**Comment by allyoucanmap** [comment]
@giohappy the improvement can be done in the MapStore2 upstream project and it could follow the same workflow that we use for bing maps api keys.

In MapStore we need to improve the setApiKeys function [here](https://github.com/geosolutions-it/MapStore2/blob/133b07e3b6e1062ef5927a72f2ef7c2715fda920/web/client/utils/ConfigUtils.js#L165-L173) by adding the case for mapbox backgrounds

```js
export const setApiKeys = function(layer) {
    if (layer.type === 'bing') {
        layer.apiKey = defaultConfig.bingApiKey;
    }
    if (layer.type === 'mapquest') {
        layer.apiKey = defaultConfig.mapquestApiKey;
    }
    if (layer.type === 'tileprovider' && ['MapBoxStyle', 'MapBox'].includes(layer.provider)) {
        // include an empty string if missing to avoid errors in the layer url template
        layer.accessToken = defaultConfig.mapboxAccessToken || '';
    }
    return layer;
};
```
then we can pass the access token from the _geonde_config.html  in the geonode_mapstore_client.html

```js
bingApiKey: '{% bing_api_key %}',
mapboxAccessToken: '{{ MAPBOX_ACCESS_TOKEN }}',
```

the fix should be quick mapstore side but then we will need to backport and update the submodule that could take some time

**Comment by giohappy** [comment]
>the fix should be quick mapstore side but then we will need to backport and update the submodule that could take some time

Can we have an ETA for this @allyoucanmap? If it's mroe then 1 week from now we will have to make the fix inside geonode client for the moment.

**Comment by allyoucanmap** [comment]
@giohappy just created a PR on MapStore2 master https://github.com/geosolutions-it/MapStore2/pull/8246

I'll let you know when the backport is ready on the stable branch

**Pull request closed without merging**
